# Copyright (c) 2019-2022, NVIDIA CORPORATION.

repos:
      - repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
              - id: isort
                # Use the config file specific to each subproject so that each
                # project can specify its own first/third-party packages.
                args: ["--config-root=python/", "--resolve-all-configs"]
                files: python/.*
                types_or: [python, cython, pyi]
      - repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
              - id: black
                files: python/cuspatial/.*
              # Explicitly specify the pyproject.toml at the repo root, not per-project.
                args: ["--config", "pyproject.toml"]
      - repo: https://github.com/PyCQA/flake8
        rev: 5.0.4
        hooks:
              - id: flake8
                args: ["--config=setup.cfg"]
                files: python/.*$
                types: [file]
                types_or: [python, cython]
                additional_dependencies: ["flake8-force"]
      - repo: local
        hooks:
              - id: clang-format
                # Using the pre-commit stage to simplify invocation of all
                # other hooks simultaneously (via any other hook stage).  This
                # can be removed if we also move to running clang-format
                # entirely through pre-commit.
                stages: [commit]
                name: clang-format
                description: Format files with ClangFormat.
                entry: clang-format -i
                language: system
                files: \.(cu|cuh|h|hpp|cpp|inl)$
                args: ['-fallback-style=none']
default_language_version:
      python: python3
